name = "RandNLA"
uuid = "0750558e-973b-4abb-bff8-906a36e76738"
authors = ["Shion Matsumoto"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
